version: '3.8'

services:
  web:
    build: .
    container_name: monitoring_app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: monitoring_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monitoring
    ports:
      - "3306:3306"
